import nftCovers from "./assets/nfts";
let projectsData = [
  {
    name: "8sian",
    website: "https://8sian-website.vercel.app/",
    opensea: "https://opensea.io/collection/8sian-main-collection",
    etherscan: "https://etherscan.io/address/0x198478f870d97d62d640368d111b979d7ca3c38f",
    preview_image: nftCovers["8SIAN.png"],
    tags: ["NFT Generation", "Website", "Bots", "Staking", "Solidity"],
  },
  {
    name: "Claylings",
    website: "https://claylings-website.vercel.app/",
    opensea: "https://opensea.io/collection/theclaylings",
    etherscan: "https://etherscan.io/address/0x8630cdeaa26d042f0f9242ca30229b425e7f243f",
    preview_image: nftCovers["Claylings.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Bullies genesis",
    website: "https://bullies-website.vercel.app/",
    opensea: "https://opensea.io/collection/basedbullies",
    etherscan: "https://basescan.io/address/0x3a8a62b77b38d5cd9a8d006ca113828bff6ab25a",
    preview_image: nftCovers["BulliesGenesis.png"],
    tags: ["NFT Generation", "Website", "Bots", "Staking", "Solidity"],
  },
  {
    name: "Early Birds",
    website: "https://early-birds-website.vercel.app/",
    opensea: "https://opensea.io/collection/earlybirdsgenesis",
    etherscan: "https://etherscan.io/address/0x01a8f00c64bbcbfe80087a14e9cc48001e8cb810",
    preview_image: nftCovers["EarlyBirds.png"],
    tags: ["NFT Generation", "Website", "Bots", "Staking", "Solidity"],
  },
  {
    name: "Cool Ape club",
    opensea: "https://opensea.io/collection/coolapeclubofficial",
    etherscan: "https://etherscan.io/address/0x01a6fa5769b13302e82f1385e18baef7e913d0a7",
    preview_image: nftCovers["CoolApeClub.png"],
    tags: ["NFT Generation", "Solidity"],
  },
  {
    name: "Artificial Intelligence Club",
    website: "https://aic-website-rust.vercel.app/",
    opensea: "https://opensea.io/collection/aicgenesis",
    etherscan: "https://etherscan.io/address/0xb78f1a96f6359ef871f594acb26900e02bfc8d00",
    preview_image: nftCovers["AIC.png"],
    tags: ["NFT Generation", "Website", "Bots", "Staking", "Solidity", "Game"],
  },
  {
    name: "Metabeasts",
    opensea: "https://opensea.io/collection/metabeasts-season-1",
    etherscan: "https://etherscan.io/address/0x62cf887b0084ea2adbce95f15dd6e8547ab53f50",
    preview_image: nftCovers["MetaBeasts.png"],
    tags: ["Solidity"],
  },
  {
    name: "Berkim",
    website: "https://berkim-website.vercel.app/",
    opensea: "https://opensea.io/collection/berkim",
    etherscan: "https://etherscan.io/address/0x64702debc7e5718640fc5a3fc599a92919c0baa3",
    preview_image: nftCovers["Berkim1984.png"],
    tags: ["NFT Generation", "Website", "Staking", "Solidity"],
  },
  {
    name: "Ishida Social Club",
    website: "https://ishida-social-club-website.vercel.app/",
    opensea: "https://opensea.io/collection/ishidasocialclub",
    etherscan: "https://etherscan.io/address/0x79731d6f294e47129b7c6eb0ae5abfa02d5c9193",
    preview_image: nftCovers["IshidaSocialClub.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Crypto Atomica",
    website: "https://crypto-atomica-website.vercel.app/",
    opensea: "https://opensea.io/collection/cryptoatomica",
    etherscan: "https://etherscan.io/address/0x29ee0d92c5d9b3982173ccea98520c59a1e58046",
    preview_image: nftCovers["CryptoAtomica.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Cozy Yety",
    opensea: "https://opensea.io/collection/cozyyety",
    etherscan: "https://etherscan.io/address/0xf0e88e3a135451d7be1fb5511f31ca45548601a4",
    preview_image: nftCovers["CozyYety.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Wackies",
    opensea: "https://opensea.io/collection/wackiesnft",
    etherscan: "https://etherscan.io/address/0xa556157eb576d59482e6146846e08f67ade26c21",
    preview_image: nftCovers["Wackies.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Wack!",
    opensea: "https://opensea.io/collection/wack-original",
    etherscan: "https://etherscan.io/address/0xcdf58775f5ac9f8fe146de68e458cf50f8854568",
    preview_image: nftCovers["Wack.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Hollow",
    opensea: "https://opensea.io/collection/hollowofficial",
    etherscan: "https://etherscan.io/address/0x291639d3884c008c29b32f2f12d05a7d2da8aa48",
    preview_image: nftCovers["Hollow.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Strangers",
    website: "https://strangers-website.vercel.app/",
    opensea: "https://opensea.io/collection/strangers-c",
    preview_image: nftCovers["Strangers.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Kaimoji",
    website: "https://kaimoji-website.vercel.app/",
    opensea: "https://opensea.io/collection/kaimojis",
    etherscan: "https://etherscan.io/address/0x14297a19f72095420d4968ed621cdc5ae6f34d87",
    preview_image: nftCovers["Kaimoji.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "AICOperatives",
    website: "https://aic-website-rust.vercel.app/",
    opensea: "https://opensea.io/collection/operatives",
    etherscan: "https://etherscan.io/address/0x0e64e8432a259c52846acdaf4e529125e840160f",
    preview_image: nftCovers["AIC_Operatives.png"],
    tags: ["NFT Generation", "Website", "Bots", "Staking", "Solidity", "Game"],
  },
  {
    name: "Kaizen Genesis Collection",
    website: "https://kaizen-website-five.vercel.app/",
    opensea: "https://opensea.io/collection/kaizengenesis",
    etherscan: "https://etherscan.io/address/0x520e08245865af97709f9d693a21901e78c7f645",
    preview_image: nftCovers["Kaizen.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
];
export default projectsData;
