import nftCovers from "./assets/nfts";

let projectsData = [
  {
    name: "8sian",
    website: "https://8sian-website.vercel.app/",
    github: "https://github.com/DevkoDev/8sian-website",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["8SIAN.png"],
    tags: ["NFT Generation", "Website", "Bots", "Staking", "Solidity"],
  },
  {
    name: "Claylings",
    website: "https://claylings-website.vercel.app/",
    github: "https://github.com/DevkoDev/claylings-website",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["Claylings.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Bullies genesis",
    website: null,
    github: "https://github.com/DevkoDev/bullies-genesis-website",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["BulliesGenesis.png"],
    tags: ["NFT Generation", "Website", "Bots", "Staking", "Solidity"],
  },

  {
    name: "Early Birds",
    website: null,
    github: "https://github.com/DevkoDev/early-birds-website",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["EarlyBirds.png"],
    tags: ["NFT Generation", "Website", "Bots", "Staking", "Solidity"],
  },  {
    name: "Cool Ape club",
    website: null,
    github: "https://github.com/DevkoDev/",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["CoolApeClub.png"],
    tags: ["NFT Generation", "Solidity"],
  },
  {
    name: "Artificial Intelligence Club",
    website: null,
    github: "https://github.com/DevkoDev/aic-website",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["AIC.png"],
    tags: ["NFT Generation", "Website", "Bots", "Staking", "Solidity", "Game"],
  },
  {
    name: "Metabeasts",
    website: null,
    github: "https://github.com/DevkoDev/",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["MetaBeasts.png"],
    tags: ["Solidity"],
  },

  {
    name: "Berkim",
    website: null,
    github: "https://github.com/DevkoDev/berkim-website",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["Berkim1984.png"],
    tags: ["NFT Generation", "Website", "Staking", "Solidity"],
  },

  {
    name: "Ishida Social Club",
    website: "https://ishida-social-club-website.vercel.app/",
    github: "https://github.com/DevkoDev/ishida-social-club-website",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["IshidaSocialClub.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Crypto Atomica",
    website: "https://crypto-atomica-website.vercel.app/",
    github: "https://github.com/DevkoDev/crypto-atomica-website",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["CryptoAtomica.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },

  {
    name: "Cozy Yety",
    website: null,
    github: "https://github.com/DevkoDev/",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["CozyYety.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Wackies",
    website: null,
    github: "https://github.com/DevkoDev/",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["Wackies.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Wack!",
    website: null,
    github: "https://github.com/DevkoDev/",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["Wack.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Hollow",
    website: null,
    github: "https://github.com/DevkoDev/",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["Hollow.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },

  {
    name: "Strangers",
    website: "https://strangers-website.vercel.app/",
    github: "https://github.com/DevkoDev/strangers-website",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["Strangers.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "Kaimoji",
    website: "https://kaimoji-website.vercel.app/",
    github: "https://github.com/DevkoDev/kaimoji-website",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["Kaimoji.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
  {
    name: "AICOperatives",
    website: null,
    github: "https://github.com/DevkoDev/",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["AIC_Operatives.png"],
    tags: ["NFT Generation", "Website", "Bots", "Staking", "Solidity", "Game"],
  },
  {
    name: "Kaizen Genesis Collection",
    website: "https://kaizen-website-five.vercel.app/",
    github: "https://github.com/DevkoDev/kaizen-website",
    opensea: "",
    etherscan: "",
    preview_image: nftCovers["Kaizen.png"],
    tags: ["NFT Generation", "Website", "Solidity"],
  },
];

export default projectsData;
